// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint
import 'dart:ffi' as ffi;

/// Dart bindings for libimagequant
class LibImageQuantBindings {
  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  LibImageQuantBindings(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  LibImageQuantBindings.fromLookup(
      ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
          lookup)
      : _lookup = lookup;

  void __va_start(
    ffi.Pointer<va_list> arg0,
  ) {
    return ___va_start(
      arg0,
    );
  }

  late final ___va_startPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<va_list>)>>(
          '__va_start');
  late final ___va_start =
      ___va_startPtr.asFunction<void Function(ffi.Pointer<va_list>)>();

  void __security_init_cookie() {
    return ___security_init_cookie();
  }

  late final ___security_init_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '__security_init_cookie');
  late final ___security_init_cookie =
      ___security_init_cookiePtr.asFunction<void Function()>();

  void __security_check_cookie(
    int _StackCookie,
  ) {
    return ___security_check_cookie(
      _StackCookie,
    );
  }

  late final ___security_check_cookiePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          '__security_check_cookie');
  late final ___security_check_cookie =
      ___security_check_cookiePtr.asFunction<void Function(int)>();

  void __report_gsfailure(
    int _StackCookie,
  ) {
    return ___report_gsfailure(
      _StackCookie,
    );
  }

  late final ___report_gsfailurePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.UintPtr)>>(
          '__report_gsfailure');
  late final ___report_gsfailure =
      ___report_gsfailurePtr.asFunction<void Function(int)>();

  late final ffi.Pointer<ffi.UintPtr> ___security_cookie =
      _lookup<ffi.UintPtr>('__security_cookie');

  int get __security_cookie => ___security_cookie.value;

  set __security_cookie(int value) => ___security_cookie.value = value;

  void _invalid_parameter_noinfo() {
    return __invalid_parameter_noinfo();
  }

  late final __invalid_parameter_noinfoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '_invalid_parameter_noinfo');
  late final __invalid_parameter_noinfo =
      __invalid_parameter_noinfoPtr.asFunction<void Function()>();

  void _invalid_parameter_noinfo_noreturn() {
    return __invalid_parameter_noinfo_noreturn();
  }

  late final __invalid_parameter_noinfo_noreturnPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function()>>(
          '_invalid_parameter_noinfo_noreturn');
  late final __invalid_parameter_noinfo_noreturn =
      __invalid_parameter_noinfo_noreturnPtr.asFunction<void Function()>();

  void _invoke_watson(
    ffi.Pointer<ffi.WChar> _Expression,
    ffi.Pointer<ffi.WChar> _FunctionName,
    ffi.Pointer<ffi.WChar> _FileName,
    int _LineNo,
    int _Reserved,
  ) {
    return __invoke_watson(
      _Expression,
      _FunctionName,
      _FileName,
      _LineNo,
      _Reserved,
    );
  }

  late final __invoke_watsonPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<ffi.WChar>,
              ffi.Pointer<ffi.WChar>,
              ffi.Pointer<ffi.WChar>,
              ffi.UnsignedInt,
              ffi.UintPtr)>>('_invoke_watson');
  late final __invoke_watson = __invoke_watsonPtr.asFunction<
      void Function(ffi.Pointer<ffi.WChar>, ffi.Pointer<ffi.WChar>,
          ffi.Pointer<ffi.WChar>, int, int)>();

  ffi.Pointer<ffi.Int> _errno() {
    return __errno();
  }

  late final __errnoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int> Function()>>('_errno');
  late final __errno = __errnoPtr.asFunction<ffi.Pointer<ffi.Int> Function()>();

  int _set_errno(
    int _Value,
  ) {
    return __set_errno(
      _Value,
    );
  }

  late final __set_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Int)>>('_set_errno');
  late final __set_errno = __set_errnoPtr.asFunction<int Function(int)>();

  int _get_errno(
    ffi.Pointer<ffi.Int> _Value,
  ) {
    return __get_errno(
      _Value,
    );
  }

  late final __get_errnoPtr =
      _lookup<ffi.NativeFunction<errno_t Function(ffi.Pointer<ffi.Int>)>>(
          '_get_errno');
  late final __get_errno =
      __get_errnoPtr.asFunction<int Function(ffi.Pointer<ffi.Int>)>();

  int __threadid() {
    return ___threadid();
  }

  late final ___threadidPtr =
      _lookup<ffi.NativeFunction<ffi.UnsignedLong Function()>>('__threadid');
  late final ___threadid = ___threadidPtr.asFunction<int Function()>();

  int __threadhandle() {
    return ___threadhandle();
  }

  late final ___threadhandlePtr =
      _lookup<ffi.NativeFunction<ffi.UintPtr Function()>>('__threadhandle');
  late final ___threadhandle = ___threadhandlePtr.asFunction<int Function()>();

  ffi.Pointer<liq_attr> liq_attr_create() {
    return _liq_attr_create();
  }

  late final _liq_attr_createPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<liq_attr> Function()>>(
          'liq_attr_create');
  late final _liq_attr_create =
      _liq_attr_createPtr.asFunction<ffi.Pointer<liq_attr> Function()>();

  ffi.Pointer<liq_attr> liq_attr_create_with_allocator(
    ffi.Pointer<ffi.Void> removed,
    ffi.Pointer<ffi.Void> unsupported,
  ) {
    return _liq_attr_create_with_allocator(
      removed,
      unsupported,
    );
  }

  late final _liq_attr_create_with_allocatorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_attr> Function(ffi.Pointer<ffi.Void>,
              ffi.Pointer<ffi.Void>)>>('liq_attr_create_with_allocator');
  late final _liq_attr_create_with_allocator =
      _liq_attr_create_with_allocatorPtr.asFunction<
          ffi.Pointer<liq_attr> Function(
              ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<liq_attr> liq_attr_copy(
    ffi.Pointer<liq_attr> orig,
  ) {
    return _liq_attr_copy(
      orig,
    );
  }

  late final _liq_attr_copyPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_attr> Function(
              ffi.Pointer<liq_attr>)>>('liq_attr_copy');
  late final _liq_attr_copy = _liq_attr_copyPtr
      .asFunction<ffi.Pointer<liq_attr> Function(ffi.Pointer<liq_attr>)>();

  void liq_attr_destroy(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_attr_destroy(
      attr,
    );
  }

  late final _liq_attr_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<liq_attr>)>>(
          'liq_attr_destroy');
  late final _liq_attr_destroy =
      _liq_attr_destroyPtr.asFunction<void Function(ffi.Pointer<liq_attr>)>();

  ffi.Pointer<liq_histogram> liq_histogram_create(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_histogram_create(
      attr,
    );
  }

  late final _liq_histogram_createPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_histogram> Function(
              ffi.Pointer<liq_attr>)>>('liq_histogram_create');
  late final _liq_histogram_create = _liq_histogram_createPtr
      .asFunction<ffi.Pointer<liq_histogram> Function(ffi.Pointer<liq_attr>)>();

  int liq_histogram_add_image(
    ffi.Pointer<liq_histogram> hist,
    ffi.Pointer<liq_attr> attr,
    ffi.Pointer<liq_image> image,
  ) {
    return _liq_histogram_add_image(
      hist,
      attr,
      image,
    );
  }

  late final _liq_histogram_add_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_histogram>, ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_image>)>>('liq_histogram_add_image');
  late final _liq_histogram_add_image = _liq_histogram_add_imagePtr.asFunction<
      int Function(ffi.Pointer<liq_histogram>, ffi.Pointer<liq_attr>,
          ffi.Pointer<liq_image>)>();

  int liq_histogram_add_colors(
    ffi.Pointer<liq_histogram> hist,
    ffi.Pointer<liq_attr> attr,
    ffi.Pointer<liq_histogram_entry> entries,
    int num_entries,
    double gamma,
  ) {
    return _liq_histogram_add_colors(
      hist,
      attr,
      entries,
      num_entries,
      gamma,
    );
  }

  late final _liq_histogram_add_colorsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<liq_histogram>,
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_histogram_entry>,
              ffi.Int,
              ffi.Double)>>('liq_histogram_add_colors');
  late final _liq_histogram_add_colors =
      _liq_histogram_add_colorsPtr.asFunction<
          int Function(ffi.Pointer<liq_histogram>, ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_histogram_entry>, int, double)>();

  int liq_histogram_add_fixed_color(
    ffi.Pointer<liq_histogram> hist,
    liq_color color,
    double gamma,
  ) {
    return _liq_histogram_add_fixed_color(
      hist,
      color,
      gamma,
    );
  }

  late final _liq_histogram_add_fixed_colorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_histogram>, liq_color,
              ffi.Double)>>('liq_histogram_add_fixed_color');
  late final _liq_histogram_add_fixed_color =
      _liq_histogram_add_fixed_colorPtr.asFunction<
          int Function(ffi.Pointer<liq_histogram>, liq_color, double)>();

  void liq_histogram_destroy(
    ffi.Pointer<liq_histogram> hist,
  ) {
    return _liq_histogram_destroy(
      hist,
    );
  }

  late final _liq_histogram_destroyPtr = _lookup<
          ffi.NativeFunction<ffi.Void Function(ffi.Pointer<liq_histogram>)>>(
      'liq_histogram_destroy');
  late final _liq_histogram_destroy = _liq_histogram_destroyPtr
      .asFunction<void Function(ffi.Pointer<liq_histogram>)>();

  int liq_set_max_colors(
    ffi.Pointer<liq_attr> attr,
    int colors,
  ) {
    return _liq_set_max_colors(
      attr,
      colors,
    );
  }

  late final _liq_set_max_colorsPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int32 Function(ffi.Pointer<liq_attr>, ffi.Int)>>(
      'liq_set_max_colors');
  late final _liq_set_max_colors = _liq_set_max_colorsPtr
      .asFunction<int Function(ffi.Pointer<liq_attr>, int)>();

  int liq_get_max_colors(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_get_max_colors(
      attr,
    );
  }

  late final _liq_get_max_colorsPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_attr>)>>(
          'liq_get_max_colors');
  late final _liq_get_max_colors =
      _liq_get_max_colorsPtr.asFunction<int Function(ffi.Pointer<liq_attr>)>();

  int liq_set_speed(
    ffi.Pointer<liq_attr> attr,
    int speed,
  ) {
    return _liq_set_speed(
      attr,
      speed,
    );
  }

  late final _liq_set_speedPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_attr>, ffi.Int)>>('liq_set_speed');
  late final _liq_set_speed =
      _liq_set_speedPtr.asFunction<int Function(ffi.Pointer<liq_attr>, int)>();

  int liq_get_speed(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_get_speed(
      attr,
    );
  }

  late final _liq_get_speedPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_attr>)>>(
          'liq_get_speed');
  late final _liq_get_speed =
      _liq_get_speedPtr.asFunction<int Function(ffi.Pointer<liq_attr>)>();

  int liq_set_min_opacity(
    ffi.Pointer<liq_attr> attr,
    int min,
  ) {
    return _liq_set_min_opacity(
      attr,
      min,
    );
  }

  late final _liq_set_min_opacityPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int32 Function(ffi.Pointer<liq_attr>, ffi.Int)>>(
      'liq_set_min_opacity');
  late final _liq_set_min_opacity = _liq_set_min_opacityPtr
      .asFunction<int Function(ffi.Pointer<liq_attr>, int)>();

  int liq_get_min_opacity(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_get_min_opacity(
      attr,
    );
  }

  late final _liq_get_min_opacityPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_attr>)>>(
          'liq_get_min_opacity');
  late final _liq_get_min_opacity =
      _liq_get_min_opacityPtr.asFunction<int Function(ffi.Pointer<liq_attr>)>();

  int liq_set_min_posterization(
    ffi.Pointer<liq_attr> attr,
    int bits,
  ) {
    return _liq_set_min_posterization(
      attr,
      bits,
    );
  }

  late final _liq_set_min_posterizationPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int32 Function(ffi.Pointer<liq_attr>, ffi.Int)>>(
      'liq_set_min_posterization');
  late final _liq_set_min_posterization = _liq_set_min_posterizationPtr
      .asFunction<int Function(ffi.Pointer<liq_attr>, int)>();

  int liq_get_min_posterization(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_get_min_posterization(
      attr,
    );
  }

  late final _liq_get_min_posterizationPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_attr>)>>(
          'liq_get_min_posterization');
  late final _liq_get_min_posterization = _liq_get_min_posterizationPtr
      .asFunction<int Function(ffi.Pointer<liq_attr>)>();

  int liq_set_quality(
    ffi.Pointer<liq_attr> attr,
    int minimum,
    int maximum,
  ) {
    return _liq_set_quality(
      attr,
      minimum,
      maximum,
    );
  }

  late final _liq_set_qualityPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<liq_attr>, ffi.Int, ffi.Int)>>('liq_set_quality');
  late final _liq_set_quality = _liq_set_qualityPtr
      .asFunction<int Function(ffi.Pointer<liq_attr>, int, int)>();

  int liq_get_min_quality(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_get_min_quality(
      attr,
    );
  }

  late final _liq_get_min_qualityPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_attr>)>>(
          'liq_get_min_quality');
  late final _liq_get_min_quality =
      _liq_get_min_qualityPtr.asFunction<int Function(ffi.Pointer<liq_attr>)>();

  int liq_get_max_quality(
    ffi.Pointer<liq_attr> attr,
  ) {
    return _liq_get_max_quality(
      attr,
    );
  }

  late final _liq_get_max_qualityPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_attr>)>>(
          'liq_get_max_quality');
  late final _liq_get_max_quality =
      _liq_get_max_qualityPtr.asFunction<int Function(ffi.Pointer<liq_attr>)>();

  void liq_set_last_index_transparent(
    ffi.Pointer<liq_attr> attr,
    int is_last,
  ) {
    return _liq_set_last_index_transparent(
      attr,
      is_last,
    );
  }

  late final _liq_set_last_index_transparentPtr = _lookup<
          ffi
          .NativeFunction<ffi.Void Function(ffi.Pointer<liq_attr>, ffi.Int)>>(
      'liq_set_last_index_transparent');
  late final _liq_set_last_index_transparent =
      _liq_set_last_index_transparentPtr
          .asFunction<void Function(ffi.Pointer<liq_attr>, int)>();

  void liq_set_log_callback(
    ffi.Pointer<liq_attr> arg0,
    ffi.Pointer<liq_log_callback_function> arg1,
    ffi.Pointer<ffi.Void> user_info,
  ) {
    return _liq_set_log_callback(
      arg0,
      arg1,
      user_info,
    );
  }

  late final _liq_set_log_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_log_callback_function>,
              ffi.Pointer<ffi.Void>)>>('liq_set_log_callback');
  late final _liq_set_log_callback = _liq_set_log_callbackPtr.asFunction<
      void Function(ffi.Pointer<liq_attr>,
          ffi.Pointer<liq_log_callback_function>, ffi.Pointer<ffi.Void>)>();

  void liq_set_log_flush_callback(
    ffi.Pointer<liq_attr> arg0,
    ffi.Pointer<liq_log_flush_callback_function> arg1,
    ffi.Pointer<ffi.Void> user_info,
  ) {
    return _liq_set_log_flush_callback(
      arg0,
      arg1,
      user_info,
    );
  }

  late final _liq_set_log_flush_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_log_flush_callback_function>,
              ffi.Pointer<ffi.Void>)>>('liq_set_log_flush_callback');
  late final _liq_set_log_flush_callback =
      _liq_set_log_flush_callbackPtr.asFunction<
          void Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_log_flush_callback_function>,
              ffi.Pointer<ffi.Void>)>();

  void liq_attr_set_progress_callback(
    ffi.Pointer<liq_attr> arg0,
    ffi.Pointer<liq_progress_callback_function> arg1,
    ffi.Pointer<ffi.Void> user_info,
  ) {
    return _liq_attr_set_progress_callback(
      arg0,
      arg1,
      user_info,
    );
  }

  late final _liq_attr_set_progress_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_progress_callback_function>,
              ffi.Pointer<ffi.Void>)>>('liq_attr_set_progress_callback');
  late final _liq_attr_set_progress_callback =
      _liq_attr_set_progress_callbackPtr.asFunction<
          void Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_progress_callback_function>,
              ffi.Pointer<ffi.Void>)>();

  void liq_result_set_progress_callback(
    ffi.Pointer<liq_result> arg0,
    ffi.Pointer<liq_progress_callback_function> arg1,
    ffi.Pointer<ffi.Void> user_info,
  ) {
    return _liq_result_set_progress_callback(
      arg0,
      arg1,
      user_info,
    );
  }

  late final _liq_result_set_progress_callbackPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
              ffi.Pointer<liq_result>,
              ffi.Pointer<liq_progress_callback_function>,
              ffi.Pointer<ffi.Void>)>>('liq_result_set_progress_callback');
  late final _liq_result_set_progress_callback =
      _liq_result_set_progress_callbackPtr.asFunction<
          void Function(
              ffi.Pointer<liq_result>,
              ffi.Pointer<liq_progress_callback_function>,
              ffi.Pointer<ffi.Void>)>();

  ffi.Pointer<liq_image> liq_image_create_rgba_rows(
    ffi.Pointer<liq_attr> attr,
    ffi.Pointer<ffi.Pointer<ffi.Void>> rows,
    int width,
    int height,
    double gamma,
  ) {
    return _liq_image_create_rgba_rows(
      attr,
      rows,
      width,
      height,
      gamma,
    );
  }

  late final _liq_image_create_rgba_rowsPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_image> Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>,
              ffi.Int,
              ffi.Int,
              ffi.Double)>>('liq_image_create_rgba_rows');
  late final _liq_image_create_rgba_rows =
      _liq_image_create_rgba_rowsPtr.asFunction<
          ffi.Pointer<liq_image> Function(ffi.Pointer<liq_attr>,
              ffi.Pointer<ffi.Pointer<ffi.Void>>, int, int, double)>();

  ffi.Pointer<liq_image> liq_image_create_rgba(
    ffi.Pointer<liq_attr> attr,
    ffi.Pointer<ffi.Void> bitmap,
    int width,
    int height,
    double gamma,
  ) {
    return _liq_image_create_rgba(
      attr,
      bitmap,
      width,
      height,
      gamma,
    );
  }

  late final _liq_image_create_rgbaPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_image> Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<ffi.Void>,
              ffi.Int,
              ffi.Int,
              ffi.Double)>>('liq_image_create_rgba');
  late final _liq_image_create_rgba = _liq_image_create_rgbaPtr.asFunction<
      ffi.Pointer<liq_image> Function(
          ffi.Pointer<liq_attr>, ffi.Pointer<ffi.Void>, int, int, double)>();

  ffi.Pointer<liq_image> liq_image_create_custom(
    ffi.Pointer<liq_attr> attr,
    ffi.Pointer<liq_image_get_rgba_row_callback> row_callback,
    ffi.Pointer<ffi.Void> user_info,
    int width,
    int height,
    double gamma,
  ) {
    return _liq_image_create_custom(
      attr,
      row_callback,
      user_info,
      width,
      height,
      gamma,
    );
  }

  late final _liq_image_create_customPtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_image> Function(
              ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_image_get_rgba_row_callback>,
              ffi.Pointer<ffi.Void>,
              ffi.Int,
              ffi.Int,
              ffi.Double)>>('liq_image_create_custom');
  late final _liq_image_create_custom = _liq_image_create_customPtr.asFunction<
      ffi.Pointer<liq_image> Function(
          ffi.Pointer<liq_attr>,
          ffi.Pointer<liq_image_get_rgba_row_callback>,
          ffi.Pointer<ffi.Void>,
          int,
          int,
          double)>();

  int liq_image_set_memory_ownership(
    ffi.Pointer<liq_image> image,
    int ownership_flags,
  ) {
    return _liq_image_set_memory_ownership(
      image,
      ownership_flags,
    );
  }

  late final _liq_image_set_memory_ownershipPtr = _lookup<
          ffi
          .NativeFunction<ffi.Int32 Function(ffi.Pointer<liq_image>, ffi.Int)>>(
      'liq_image_set_memory_ownership');
  late final _liq_image_set_memory_ownership =
      _liq_image_set_memory_ownershipPtr
          .asFunction<int Function(ffi.Pointer<liq_image>, int)>();

  int liq_image_set_background(
    ffi.Pointer<liq_image> img,
    ffi.Pointer<liq_image> background_image,
  ) {
    return _liq_image_set_background(
      img,
      background_image,
    );
  }

  late final _liq_image_set_backgroundPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_image>,
              ffi.Pointer<liq_image>)>>('liq_image_set_background');
  late final _liq_image_set_background =
      _liq_image_set_backgroundPtr.asFunction<
          int Function(ffi.Pointer<liq_image>, ffi.Pointer<liq_image>)>();

  int liq_image_set_importance_map(
    ffi.Pointer<liq_image> img,
    ffi.Pointer<ffi.UnsignedChar> buffer,
    int buffer_size,
    int memory_handling,
  ) {
    return _liq_image_set_importance_map(
      img,
      buffer,
      buffer_size,
      memory_handling,
    );
  }

  late final _liq_image_set_importance_mapPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<liq_image>,
              ffi.Pointer<ffi.UnsignedChar>,
              ffi.Size,
              ffi.Int32)>>('liq_image_set_importance_map');
  late final _liq_image_set_importance_map =
      _liq_image_set_importance_mapPtr.asFunction<
          int Function(ffi.Pointer<liq_image>, ffi.Pointer<ffi.UnsignedChar>,
              int, int)>();

  int liq_image_add_fixed_color(
    ffi.Pointer<liq_image> img,
    liq_color color,
  ) {
    return _liq_image_add_fixed_color(
      img,
      color,
    );
  }

  late final _liq_image_add_fixed_colorPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<liq_image>, liq_color)>>('liq_image_add_fixed_color');
  late final _liq_image_add_fixed_color = _liq_image_add_fixed_colorPtr
      .asFunction<int Function(ffi.Pointer<liq_image>, liq_color)>();

  int liq_image_get_width(
    ffi.Pointer<liq_image> img,
  ) {
    return _liq_image_get_width(
      img,
    );
  }

  late final _liq_image_get_widthPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_image>)>>(
          'liq_image_get_width');
  late final _liq_image_get_width = _liq_image_get_widthPtr
      .asFunction<int Function(ffi.Pointer<liq_image>)>();

  int liq_image_get_height(
    ffi.Pointer<liq_image> img,
  ) {
    return _liq_image_get_height(
      img,
    );
  }

  late final _liq_image_get_heightPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_image>)>>(
          'liq_image_get_height');
  late final _liq_image_get_height = _liq_image_get_heightPtr
      .asFunction<int Function(ffi.Pointer<liq_image>)>();

  void liq_image_destroy(
    ffi.Pointer<liq_image> img,
  ) {
    return _liq_image_destroy(
      img,
    );
  }

  late final _liq_image_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<liq_image>)>>(
          'liq_image_destroy');
  late final _liq_image_destroy =
      _liq_image_destroyPtr.asFunction<void Function(ffi.Pointer<liq_image>)>();

  int liq_histogram_quantize(
    ffi.Pointer<liq_histogram> input_hist,
    ffi.Pointer<liq_attr> options,
    ffi.Pointer<ffi.Pointer<liq_result>> result_output,
  ) {
    return _liq_histogram_quantize(
      input_hist,
      options,
      result_output,
    );
  }

  late final _liq_histogram_quantizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_histogram>, ffi.Pointer<liq_attr>,
              ffi.Pointer<ffi.Pointer<liq_result>>)>>('liq_histogram_quantize');
  late final _liq_histogram_quantize = _liq_histogram_quantizePtr.asFunction<
      int Function(ffi.Pointer<liq_histogram>, ffi.Pointer<liq_attr>,
          ffi.Pointer<ffi.Pointer<liq_result>>)>();

  int liq_image_quantize(
    ffi.Pointer<liq_image> input_image,
    ffi.Pointer<liq_attr> options,
    ffi.Pointer<ffi.Pointer<liq_result>> result_output,
  ) {
    return _liq_image_quantize(
      input_image,
      options,
      result_output,
    );
  }

  late final _liq_image_quantizePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_image>, ffi.Pointer<liq_attr>,
              ffi.Pointer<ffi.Pointer<liq_result>>)>>('liq_image_quantize');
  late final _liq_image_quantize = _liq_image_quantizePtr.asFunction<
      int Function(ffi.Pointer<liq_image>, ffi.Pointer<liq_attr>,
          ffi.Pointer<ffi.Pointer<liq_result>>)>();

  int liq_set_dithering_level(
    ffi.Pointer<liq_result> res,
    double dither_level,
  ) {
    return _liq_set_dithering_level(
      res,
      dither_level,
    );
  }

  late final _liq_set_dithering_levelPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<liq_result>, ffi.Float)>>('liq_set_dithering_level');
  late final _liq_set_dithering_level = _liq_set_dithering_levelPtr
      .asFunction<int Function(ffi.Pointer<liq_result>, double)>();

  int liq_set_output_gamma(
    ffi.Pointer<liq_result> res,
    double gamma,
  ) {
    return _liq_set_output_gamma(
      res,
      gamma,
    );
  }

  late final _liq_set_output_gammaPtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(
              ffi.Pointer<liq_result>, ffi.Double)>>('liq_set_output_gamma');
  late final _liq_set_output_gamma = _liq_set_output_gammaPtr
      .asFunction<int Function(ffi.Pointer<liq_result>, double)>();

  double liq_get_output_gamma(
    ffi.Pointer<liq_result> result,
  ) {
    return _liq_get_output_gamma(
      result,
    );
  }

  late final _liq_get_output_gammaPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<liq_result>)>>(
          'liq_get_output_gamma');
  late final _liq_get_output_gamma = _liq_get_output_gammaPtr
      .asFunction<double Function(ffi.Pointer<liq_result>)>();

  ffi.Pointer<liq_palette> liq_get_palette(
    ffi.Pointer<liq_result> result,
  ) {
    return _liq_get_palette(
      result,
    );
  }

  late final _liq_get_palettePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_palette> Function(
              ffi.Pointer<liq_result>)>>('liq_get_palette');
  late final _liq_get_palette = _liq_get_palettePtr
      .asFunction<ffi.Pointer<liq_palette> Function(ffi.Pointer<liq_result>)>();

  int liq_write_remapped_image(
    ffi.Pointer<liq_result> result,
    ffi.Pointer<liq_image> input_image,
    ffi.Pointer<ffi.Void> buffer,
    int buffer_size,
  ) {
    return _liq_write_remapped_image(
      result,
      input_image,
      buffer,
      buffer_size,
    );
  }

  late final _liq_write_remapped_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Int32 Function(ffi.Pointer<liq_result>, ffi.Pointer<liq_image>,
              ffi.Pointer<ffi.Void>, ffi.Size)>>('liq_write_remapped_image');
  late final _liq_write_remapped_image =
      _liq_write_remapped_imagePtr.asFunction<
          int Function(ffi.Pointer<liq_result>, ffi.Pointer<liq_image>,
              ffi.Pointer<ffi.Void>, int)>();

  int liq_write_remapped_image_rows(
    ffi.Pointer<liq_result> result,
    ffi.Pointer<liq_image> input_image,
    ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>> row_pointers,
  ) {
    return _liq_write_remapped_image_rows(
      result,
      input_image,
      row_pointers,
    );
  }

  late final _liq_write_remapped_image_rowsPtr = _lookup<
          ffi.NativeFunction<
              ffi.Int32 Function(
                  ffi.Pointer<liq_result>,
                  ffi.Pointer<liq_image>,
                  ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>)>>(
      'liq_write_remapped_image_rows');
  late final _liq_write_remapped_image_rows =
      _liq_write_remapped_image_rowsPtr.asFunction<
          int Function(ffi.Pointer<liq_result>, ffi.Pointer<liq_image>,
              ffi.Pointer<ffi.Pointer<ffi.UnsignedChar>>)>();

  double liq_get_quantization_error(
    ffi.Pointer<liq_result> result,
  ) {
    return _liq_get_quantization_error(
      result,
    );
  }

  late final _liq_get_quantization_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<liq_result>)>>(
          'liq_get_quantization_error');
  late final _liq_get_quantization_error = _liq_get_quantization_errorPtr
      .asFunction<double Function(ffi.Pointer<liq_result>)>();

  int liq_get_quantization_quality(
    ffi.Pointer<liq_result> result,
  ) {
    return _liq_get_quantization_quality(
      result,
    );
  }

  late final _liq_get_quantization_qualityPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_result>)>>(
          'liq_get_quantization_quality');
  late final _liq_get_quantization_quality = _liq_get_quantization_qualityPtr
      .asFunction<int Function(ffi.Pointer<liq_result>)>();

  double liq_get_remapping_error(
    ffi.Pointer<liq_result> result,
  ) {
    return _liq_get_remapping_error(
      result,
    );
  }

  late final _liq_get_remapping_errorPtr =
      _lookup<ffi.NativeFunction<ffi.Double Function(ffi.Pointer<liq_result>)>>(
          'liq_get_remapping_error');
  late final _liq_get_remapping_error = _liq_get_remapping_errorPtr
      .asFunction<double Function(ffi.Pointer<liq_result>)>();

  int liq_get_remapping_quality(
    ffi.Pointer<liq_result> result,
  ) {
    return _liq_get_remapping_quality(
      result,
    );
  }

  late final _liq_get_remapping_qualityPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function(ffi.Pointer<liq_result>)>>(
          'liq_get_remapping_quality');
  late final _liq_get_remapping_quality = _liq_get_remapping_qualityPtr
      .asFunction<int Function(ffi.Pointer<liq_result>)>();

  void liq_result_destroy(
    ffi.Pointer<liq_result> arg0,
  ) {
    return _liq_result_destroy(
      arg0,
    );
  }

  late final _liq_result_destroyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Pointer<liq_result>)>>(
          'liq_result_destroy');
  late final _liq_result_destroy = _liq_result_destroyPtr
      .asFunction<void Function(ffi.Pointer<liq_result>)>();

  int liq_version() {
    return _liq_version();
  }

  late final _liq_versionPtr =
      _lookup<ffi.NativeFunction<ffi.Int Function()>>('liq_version');
  late final _liq_version = _liq_versionPtr.asFunction<int Function()>();

  ffi.Pointer<liq_result> liq_quantize_image(
    ffi.Pointer<liq_attr> options,
    ffi.Pointer<liq_image> input_image,
  ) {
    return _liq_quantize_image(
      options,
      input_image,
    );
  }

  late final _liq_quantize_imagePtr = _lookup<
      ffi.NativeFunction<
          ffi.Pointer<liq_result> Function(ffi.Pointer<liq_attr>,
              ffi.Pointer<liq_image>)>>('liq_quantize_image');
  late final _liq_quantize_image = _liq_quantize_imagePtr.asFunction<
      ffi.Pointer<liq_result> Function(
          ffi.Pointer<liq_attr>, ffi.Pointer<liq_image>)>();
}

typedef va_list = ffi.Pointer<ffi.Char>;

final class __crt_locale_data_public extends ffi.Struct {
  external ffi.Pointer<ffi.UnsignedShort> _locale_pctype;

  @ffi.Int()
  external int _locale_mb_cur_max;

  @ffi.UnsignedInt()
  external int _locale_lc_codepage;
}

final class __crt_locale_pointers extends ffi.Struct {
  external ffi.Pointer<__crt_locale_data> locinfo;

  external ffi.Pointer<__crt_multibyte_data> mbcinfo;
}

final class __crt_locale_data extends ffi.Opaque {}

final class __crt_multibyte_data extends ffi.Opaque {}

final class _Mbstatet extends ffi.Struct {
  @ffi.UnsignedLong()
  external int _Wchar;

  @ffi.UnsignedShort()
  external int _Byte;

  @ffi.UnsignedShort()
  external int _State;
}

typedef errno_t = ffi.Int;
typedef Darterrno_t = int;

final class liq_attr extends ffi.Opaque {}

final class liq_image extends ffi.Opaque {}

final class liq_result extends ffi.Opaque {}

final class liq_histogram extends ffi.Opaque {}

final class liq_color extends ffi.Struct {
  @ffi.UnsignedChar()
  external int r;

  @ffi.UnsignedChar()
  external int g;

  @ffi.UnsignedChar()
  external int b;

  @ffi.UnsignedChar()
  external int a;
}

final class liq_palette extends ffi.Struct {
  @ffi.UnsignedInt()
  external int count;

  @ffi.Array.multi([256])
  external ffi.Array<liq_color> entries;
}

abstract class liq_error {
  static const int LIQ_OK = 0;
  static const int LIQ_QUALITY_TOO_LOW = 99;
  static const int LIQ_VALUE_OUT_OF_RANGE = 100;
  static const int LIQ_OUT_OF_MEMORY = 101;
  static const int LIQ_ABORTED = 102;
  static const int LIQ_BITMAP_NOT_AVAILABLE = 103;
  static const int LIQ_BUFFER_TOO_SMALL = 104;
  static const int LIQ_INVALID_POINTER = 105;
  static const int LIQ_UNSUPPORTED = 106;
}

abstract class liq_ownership {
  static const int LIQ_OWN_ROWS = 4;
  static const int LIQ_OWN_PIXELS = 8;
  static const int LIQ_COPY_PIXELS = 16;
}

final class liq_histogram_entry extends ffi.Struct {
  external liq_color color;

  @ffi.UnsignedInt()
  external int count;
}

typedef liq_log_callback_function = ffi.NativeFunction<
    ffi.Void Function(
        ffi.Pointer<liq_attr>, ffi.Pointer<ffi.Char>, ffi.Pointer<ffi.Void>)>;
typedef liq_log_flush_callback_function = ffi.NativeFunction<
    ffi.Void Function(ffi.Pointer<liq_attr>, ffi.Pointer<ffi.Void>)>;
typedef liq_progress_callback_function = ffi.NativeFunction<
    ffi.Int Function(
        ffi.Float progress_percent, ffi.Pointer<ffi.Void> user_info)>;
typedef liq_image_get_rgba_row_callback = ffi.NativeFunction<
    ffi.Void Function(ffi.Pointer<liq_color> row_out, ffi.Int row,
        ffi.Int width, ffi.Pointer<ffi.Void> user_info)>;

const int LIQ_VERSION = 40003;

const String LIQ_VERSION_STRING = '4.0.3';

const int _VCRT_COMPILER_PREPROCESSOR = 1;

const int _SAL_VERSION = 20;

const int __SAL_H_VERSION = 180000000;

const int _USE_DECLSPECS_FOR_SAL = 0;

const int _USE_ATTRIBUTES_FOR_SAL = 0;

const int _CRT_PACKING = 8;

const int _VCRUNTIME_DISABLED_WARNINGS = 4514;

const int _HAS_EXCEPTIONS = 1;

const int _WCHAR_T_DEFINED = 1;

const int NULL = 0;

const int _HAS_CXX17 = 0;

const int _HAS_CXX20 = 0;

const int _HAS_CXX23 = 0;

const int _HAS_CXX26 = 0;

const int _HAS_NODISCARD = 1;

const int _ARM_WINAPI_PARTITION_DESKTOP_SDK_AVAILABLE = 1;

const int _CRT_BUILD_DESKTOP_APP = 1;

const int _UCRT_DISABLED_WARNINGS = 4324;

const int _ARGMAX = 100;

const int _TRUNCATE = -1;

const int _CRT_INT_MAX = 2147483647;

const int _CRT_SIZE_MAX = -1;

const String __FILEW__ = 'C';

const int _CRT_FUNCTIONS_REQUIRED = 1;

const int _CRT_HAS_CXX17 = 0;

const int _CRT_HAS_C11 = 0;

const int _CRT_INTERNAL_NONSTDC_NAMES = 1;

const int __STDC_SECURE_LIB__ = 200411;

const int __GOT_SECURE_LIB__ = 200411;

const int __STDC_WANT_SECURE_LIB__ = 1;

const int _SECURECRT_FILL_BUFFER_PATTERN = 254;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES = 0;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_COUNT = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES = 1;

const int _CRT_SECURE_CPP_OVERLOAD_STANDARD_NAMES_MEMORY = 0;

const int _CRT_SECURE_CPP_OVERLOAD_SECURE_NAMES_MEMORY = 0;
